# we only CI the master, release branches, tags and PRs
#if: tag IS present OR type = pull_request OR ((branch = master OR branch =~ release-*) AND type = push)

language: python
# cache package wheels (1 cache per python version)
cache: pip
# newer python versions are available only on xenial (while some older only on trusty) Ubuntu distribution
dist: xenial

env:
  TOXENV=py
  EXTRA_ARGS="-n 12"

jobs:
  include:
  - name: "run test suite with python 3.6"
    python: 3.6
  - name: "run test suite with python 3.6"
    python: 3.6
  - name: "run test suite with python 3.7"
    python: 3.7
  - name: "type check"
    python: 3.7
    env:
    - TOXENV=type
    - EXTRA_ARGS=
  - name: "style with flake8"
    python: 3.7
    env:
    - TOXENV=lint
    - EXTRA_ARGS=

install:
- pip install -U pip setuptools
- pip install -U tox==3.9.0
- tox --notest

script:
- tox -- $EXTRA_ARGS
